const CONSTANTS = {}

// CAMERA

CONSTANTS.CAMERA_SPAWN_POSITION_X = 0;
CONSTANTS.CAMERA_SPAWN_POSITION_Y = 0;
CONSTANTS.CAMERA_SPAWN_POSITION_Z = 20;

CONSTANTS.CAMERA_SPAWN_ROTATION_X = 0;
CONSTANTS.CAMERA_SPAWN_ROTATION_Y = 0;
CONSTANTS.CAMERA_SPAWN_ROTATION_Z = 0;

// KINECT

CONSTANTS.KINECT_SPAWN_POSITION_X = 0;
CONSTANTS.KINECT_SPAWN_POSITION_Y = 0;
CONSTANTS.KINECT_SPAWN_POSITION_Z = 12;

CONSTANTS.KINECT_SPAWN_ROTATION_X = 0;
CONSTANTS.KINECT_SPAWN_ROTATION_Y = 0;
CONSTANTS.KINECT_SPAWN_ROTATION_Z = 0;

CONSTANTS.KINECT_SPAWN_WIDTH = 1.9;
CONSTANTS.KINECT_SPAWN_HEIGHT = 1;

// SANDBOX
CONSTANTS.SANDBOX_SPAWN_WIDTH = 30;
CONSTANTS.SANDBOX_SPAWN_HEIGHT = 3;

export default CONSTANTS;
