const CONSTANTS = {}

CONSTANTS.CAMERA_SPAWN_POSITION_X = 0;
CONSTANTS.CAMERA_SPAWN_POSITION_Y = 0;
CONSTANTS.CAMERA_SPAWN_POSITION_Z = 12;

CONSTANTS.CAMERA_SPAWN_ROTATION_X = 0;
CONSTANTS.CAMERA_SPAWN_ROTATION_Y = 0;
CONSTANTS.CAMERA_SPAWN_ROTATION_Z = 0;

export default CONSTANTS;
