const CONSTANTS = {}

// CAMERA

CONSTANTS.CAMERA_SPAWN_POSITION_X = 0;
CONSTANTS.CAMERA_SPAWN_POSITION_Y = 0;
CONSTANTS.CAMERA_SPAWN_POSITION_Z = 20;

CONSTANTS.CAMERA_SPAWN_ROTATION_X = 0;
CONSTANTS.CAMERA_SPAWN_ROTATION_Y = 0;
CONSTANTS.CAMERA_SPAWN_ROTATION_Z = 0;

// KINECT

CONSTANTS.KINECT_SPAWN_POSITION_X = 0;
CONSTANTS.KINECT_SPAWN_POSITION_Y = 0;
CONSTANTS.KINECT_SPAWN_POSITION_Z = 12;

CONSTANTS.KINECT_SPAWN_ROTATION_X = 0;
CONSTANTS.KINECT_SPAWN_ROTATION_Y = 0;
CONSTANTS.KINECT_SPAWN_ROTATION_Z = 0;

CONSTANTS.KINECT_SPAWN_WIDTH = 1.9;
CONSTANTS.KINECT_SPAWN_HEIGHT = 1;

CONSTANTS.KINECT_COLOR = '#00ff00';

// PROJECTOR

CONSTANTS.PROJECTOR_SPAWN_POSITION_X = 0;
CONSTANTS.PROJECTOR_SPAWN_POSITION_Y = 0;
CONSTANTS.PROJECTOR_SPAWN_POSITION_Z = 0;

CONSTANTS.PROJECTOR_SPAWN_POSITION_POV_X = 0;
CONSTANTS.PROJECTOR_SPAWN_POSITION_POV_Y = 0;
CONSTANTS.PROJECTOR_SPAWN_POSITION_POV_Z = 11;

CONSTANTS.PROJECTOR_SPAWN_ROTATION_X = 0;
CONSTANTS.PROJECTOR_SPAWN_ROTATION_Y = 0;
CONSTANTS.PROJECTOR_SPAWN_ROTATION_Z = 0;

CONSTANTS.PROJECTOR_SPAWN_WIDTH = 14;
CONSTANTS.PROJECTOR_SPAWN_HEIGHT = 8;

CONSTANTS.PROJECTOR_COLOR = '#8a8a5c';

// SANDBOX
CONSTANTS.SANDBOX_SPAWN_WIDTH = 15;
CONSTANTS.SANDBOX_SPAWN_HEIGHT = 9;

export default CONSTANTS;
